dvpOAuth/__init__.py,sha256=W3vU8erXur5BtSB97I1HXj07F5FBEQSjI9Z8qmJoklQ,163
dvpOAuth/class_OAuth.py,sha256=TFOMzpt9GMuxCKDZ9UYH3-EipLko3y9OSx8M_EzbocE,12415
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=y-S4zD5BGEWKHVfJKGyy5teIeV2XdWrMXeRubAW54Ek,685
dvpOAuth-0.0.12.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.12.dist-info/METADATA,sha256=vtGW8KHBdW6FZjrjf9XUtxAQaOGrvCqyD5-HgckSS68,992
dvpOAuth-0.0.12.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.12.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.12.dist-info/RECORD,,
