dvpOAuth/__init__.py,sha256=EYmaV4faEu9UHoAFdb1y16eQf-tzcuQm3OmnGSN5qZs,163
dvpOAuth/class_OAuth.py,sha256=nxmb0p4cNtlkBnONq8BDLvzJpzqg02jhB4-GE_M8Z98,11926
dvpOAuth/error.py,sha256=Y3BjsevsSGMDVVdn6ztiQMcGNtB6lySkNPoL7y4BT-Q,131
dvpOAuth/util.py,sha256=y-S4zD5BGEWKHVfJKGyy5teIeV2XdWrMXeRubAW54Ek,685
dvpOAuth-0.0.10.dist-info/LICENSE,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
dvpOAuth-0.0.10.dist-info/METADATA,sha256=nhF8Zo_bqyX5CjGgDTXlZPiNDOpTWyIpJSyZEnXcJMk,992
dvpOAuth-0.0.10.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
dvpOAuth-0.0.10.dist-info/top_level.txt,sha256=14UgmlstFHh0UvlWIljRlFO26u2OesXzFC8SsWFZRmw,9
dvpOAuth-0.0.10.dist-info/RECORD,,
