from cgc.commands.exceptions import ResponseException


class AuthCommandException(ResponseException):
    pass
